name: coreysblackwell
favicon: null
layout_spectrum: 0.967960681533441
typography_spectrum: 0.6014762758277357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#cccccc'
    - '#02e4f8'
    - '#0265ab'
  brandStrength: 0.9375
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
