name: coreysblackwell
favicon: null
layout_spectrum: 0.967960681533441
typography_spectrum: 0.6014762758277357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9485045673791319
  lightness: 0.1371958756353706
  saturation: 0.1697278255596757
  rhythmicContrast: 0.3959669976029545
purpose: []
